"""Config CLI commands extracted from cli.py."""

from rich.prompt import Prompt

from ...utils.config import config


def handle_config_init() -> int:
    """Handle config --init command.

    This will interactively collect API keys and create/update the .env file.
    """
    from pathlib import Path

    try:
        project_root = Path.cwd()
        env_path = project_root / ".env"

        print("🔧 Initializing ScanAI configuration...")
        print("This will help you set up your API keys interactively.\n")

        # Collect API keys interactively
        api_keys = {}

        # Gemini API Keys (Required)
        print("🤖 Google Gemini API Keys (Required for AI analysis)")
        print("   Get your keys from: https://aistudio.google.com/")
        print("   Multiple keys help with rate limiting and redundancy.\n")

        while True:
            try:
                num_keys = int(Prompt.ask("   How many Gemini API keys do you want to configure?", default="1"))
                if num_keys > 0:
                    break
                print("   ❌ Please enter at least 1 key.")
            except ValueError:
                print("   ❌ Please enter a valid number.")

        if num_keys == 1:
            gemini_keys = [Prompt.ask("   Enter your Gemini API key")]
        else:
            print(f"   Enter {num_keys} Gemini API keys (comma-separated):")
            keys_input = Prompt.ask("   Keys")
            gemini_keys = [key.strip() for key in keys_input.split(',') if key.strip()]

            while len(gemini_keys) != num_keys:
                print(f"   ❌ Expected {num_keys} keys, but got {len(gemini_keys)}. Please try again.")
                keys_input = Prompt.ask("   Keys")
                gemini_keys = [key.strip() for key in keys_input.split(',') if key.strip()]

        api_keys['GEMINI_API_KEYS'] = ','.join(gemini_keys)
        print(f"   ✅ Configured {len(gemini_keys)} Gemini API key(s)\n")

        # VirusTotal API Key (Optional)
        print("🛡️  VirusTotal API Key (Optional - for malware scanning)")
        print("   Get your key from: https://www.virustotal.com/")
        print("   Leave empty to skip.\n")

        vt_key = Prompt.ask("   Enter your VirusTotal API key (or press Enter to skip)", default="")
        if vt_key.strip():
            api_keys['VIRUSTOTAL_API_KEY'] = vt_key.strip()
            print("   ✅ VirusTotal API key configured\n")
        else:
            api_keys['VIRUSTOTAL_API_KEY'] = ""
            print("   ⏭️  VirusTotal API key skipped\n")

        # URLScan API Key (Optional)
        print("🌐 URLScan.io API Key (Optional - for URL analysis)")
        print("   Get your key from: https://urlscan.io/")
        print("   Leave empty to skip.\n")

        urlscan_key = Prompt.ask("   Enter your URLScan.io API key (or press Enter to skip)", default="")
        if urlscan_key.strip():
            api_keys['URLSCAN_API_KEY'] = urlscan_key.strip()
            print("   ✅ URLScan.io API key configured\n")
        else:
            api_keys['URLSCAN_API_KEY'] = ""
            print("   ⏭️  URLScan.io API key skipped\n")

        # Create or update .env file
        env_content = f"""# ScanAI .env configuration
# Auto-generated by scanai config --init

# Required: Google Gemini API Keys for AI analysis (supports multiple keys, comma-separated)
# Get your keys from: https://aistudio.google.com/
GEMINI_API_KEYS="{api_keys['GEMINI_API_KEYS']}"

# Optional: VirusTotal API Key for malware scanning
# Get your key from: https://www.virustotal.com/
VIRUSTOTAL_API_KEY="{api_keys['VIRUSTOTAL_API_KEY']}"

# Optional: URLScan.io API Key for URL analysis
# Get your key from: https://urlscan.io/
URLSCAN_API_KEY="{api_keys['URLSCAN_API_KEY']}"
"""

        env_path.write_text(env_content)
        print(f"✅ Configuration saved to: {env_path}")

        # Also create a TOML template for non-secret settings (optional)
        config.save_toml_template()

        print("\n🎉 Configuration complete!")
        print("\n📋 Summary:")
        print(f"   • Gemini API Keys: {len(gemini_keys)} configured")
        print(f"   • VirusTotal API Key: {'✅ Configured' if api_keys['VIRUSTOTAL_API_KEY'] else '⏭️  Skipped'}")
        print(f"   • URLScan.io API Key: {'✅ Configured' if api_keys['URLSCAN_API_KEY'] else '⏭️  Skipped'}")

        print("\n🔍 Run 'scanai config --check' to verify your configuration.")
        print("🚀 You can now start scanning!")

        return 0

    except KeyboardInterrupt:
        print("\n\n❌ Configuration cancelled by user.")
        return 1
    except Exception as e:
        print(f"\n❌ Failed to create configuration: {str(e)}")
        return 1


def handle_config_check() -> int:
    """Handle config --check command."""
    try:
        print("🔍 Checking ScanAI configuration...")
        print()

        # Show config file locations
        config.show_config_locations()
        print()

        # Check API key status
        validation = config.validate_api_keys()

        print("🔑 API Keys Status:")
        key_requirements = {
            'gemini': 'Required',
            'virustotal': 'Optional',
            'urlscan': 'Optional'
        }

        for key, valid in validation.items():
            status_icon = "✅" if valid else "❌"
            status_text = "[green]Configured[/green]" if valid else "[red]Missing[/red]"
            required = key_requirements.get(key, 'Unknown')
            print(f"  {status_icon} {key.upper()}: {status_text} ({required})")

        # Show Gemini key count if configured
        if validation.get('gemini', False):
            gemini_keys = config.gemini_api_keys
            print(f"  🔄 GEMINI_KEYS: ✅ {len(gemini_keys)} configured")

        print()
        print("📊 Scan Settings:")
        print(f"  ⏱️  Nmap Timeout: {config.nmap_timeout}s")
        print(f"  🔄 Scan Timeout: {config.scan_timeout}s")
        print(f"  🔍 Max Subdomains: {config.max_subdomains}")
        print(f"  📝 Verbose Output: {'Enabled' if config.verbose else 'Disabled'}")
        print(f"  📄 JSON Output: {'Enabled' if config.json_output else 'Disabled'}")

        # Overall status
        gemini_ok = validation.get('gemini', False)
        if gemini_ok:
            print("\n✅ Configuration Status: [green]READY[/green] - ScanAI is properly configured!")
            return 0
        else:
            print("\n❌ Configuration Status: [red]INCOMPLETE[/red] - Run 'scanai config --init' to configure API keys")
            return 1

    except Exception as e:
        print(f"❌ Failed to check configuration: {str(e)}")
        return 1
